title: Računalniški praktikum
author: Katja Berčič, Matija Pretnar
copyright: "2024"

# Skrita poglavja se sploh ne zgradijo: brez strani, brez iskalnega indeksa.
# Poglavje razkrijemo tako, da ga odstranimo od tod IN odkomentiramo v _toc.yml.
exclude_patterns:
  - 02-git-in-markdown.md
  - 03-html.md
  - 04-css.md
  - 05-utrdimo-osnove.md
  - 06-uvod-v-latex.md
  - 07-okolja-in-sklicevanje.md
  - 08-predstavitve.md
  - 09-risanje.md
  - 10-razpredelnice.md
  - 11-racunanje-z-mathematico.md
  - 12-risanje-in-enacbe.md
  - 13-animiranje-vektorji-matrike.md
repository:
  url: 'https://github.com/katjabercic/racunalniski-praktikum'

# sphinx:
#   extra_extensions:
#     - sphinx_proof
#   local_extensions:
#     semantic: 'extensions/'

# semantic:
#   # This can be any URI identifying your course; need not be an actual URL
#   namespace: https://Nicolas.Thiery.name/Enseignement/Info111
#   # This is were you can insert alignments for the terminology of your course
#   symdecls:
#     - verbalization: informatique
#       en: computer science
#       mathhub: '[smglom/cs]mod?computer-science?CS'